Fix Issue #206 "Some Tumblr blogs are falsely reported as offline"
TumblThreeApp/TumblThree pull request #213
Opened 2022-02-10 00:00 UTC by kulesy

## Title

**Fixing:** Listed blogs in manager view that have subsequently been switched to hidden on Tumblr will appear - upon status check - as offline.

## Description

**How this has been fixed:** 
When executing a status check, the URL of the selected blog will be recognized to have a hidden route which will trigger the blog type to be tmblrpriv and the URL to have a hidden route while the status of the blog is still online. 
With this new URL, a get request is sent to the API which, if the user is logged in, will return 200 OK and the app runs normally. 
However if the get request returns a 404 NotFound an exception will be thrown and caught. Knowing that the blog is hidden the most likely reason for the exception will be because the user is not logged in, therefore an the "must be logged in" error message is displayed.

## Issue Resolution

This Pull Request Fixes #206 

## Proposed Changes

 - ITumblrBlogDetector to be injected into the TumblrBlogCrawler - to identify blog as hidden
 - GetUrlRedirection() in TumblrBlogDetector to be changed from private to public - to get the hidden blog URL

2022-02-10 15:54 UTC, thomas694 commented
Let's look at the code. Ok, from your questions and our descriptions, I had a different picture in my head. No problem, my imagination.

Is `IsBlogOnlineAsync` only called when doing a manual check initiated through the context menu or also internally while processing and so on? I'm not sure about side effects and would only implement it for a manual check. Is it possible to add an unchecked in the meantime hidden blog to the queue and crawl?
Looking inside a tmblrpriv file, I think normally the change of the URL wouldn't be necessary, as the API is still accessed with the normal URL, or it's reconstructed somewhere in the code.
It introduces a new dependency (`TumblrBlogDetector`), ok. But then the tmblr crawler changes the type of its assigned blog and checks a tmblrpriv blog with his own code. I haven't run it. That might work at the moment, but is a mixture of concerns. It's not so good in my opinion. One crawler only knows how to handle its own type.
I think, it would be better to do the decision making and blog (type) changes outside where the call to `IsBlogOnlineAsync` is done, inside e.g. the `ManagerController` you mentioned before.

What do you think about it? Wouldn't this approach be cleaner?

2022-02-10 19:38 UTC, kulesy commented
Yes that looks to be a much better way of doing it, I should've looked a further back in the scope of status checks, my bad. Could you explain further what you mean by an unchecked for hidden blogs to be crawled. Do you mean while the online status is displayed and the blog is hidden it should still be able to be crawled?

2022-02-11 00:05 UTC, kulesy commented
An online check is done within the the crawling controller (when the crawl is initiated), however the online status is checked within the type specific ICrawler class (eg. TumblrBlogCrawler) through the IsBlogOnlineAsync() which is where I had the hidden check originally. So I believe the check might actually have to be done through the TumblrBlogCrawler class and change the blog type there, which should be fine as a new instance of a TumblrHiddenCrawler class will be made for the actual crawling process.

2022-02-11 14:04 UTC, thomas694 commented
Yes, you're right in terms of flow where it's going through. But interface wise the individual crawler doesn't need to know, whether there is another crawler that can process that (changed) type and how, or try to do it itself.
After changing the type it's going on with `await GetApiPageWithRetryAsync(0)`, which seems to work at the moment, because internally nearly the same thing is done. But somehow it's mingling a bit. Also I'm thinking about the change of the URL, which you most probably need for continuing in the current crawler, but maybe makes more trouble in the future, because that changes more often than the standardized blog (domain) name.
Maybe you can have a look, whether it's possible to move this logic out of the crawler to the outside. If, after thinking about it or maybe a small try, you come to the conclusion that it gets too cumbersome to do it from outside, we can stick with your first way.

2022-02-12 02:16 UTC, kulesy commented
Okay I've got the hidden blog type updating outside the crawlers now. However it required the crawler controller to be dependent on the TumblrBlogDetector. So now the hidden blog detection works for both the status check and the crawling of queued blogs. Therefore I believe you don't have to worry about any bugs occuring with incorrect blog types in specific crawlers. It also addresses if the user is signed in for hidden blogs without the need of the URL change which was a bit clunky.

2022-02-12 22:04 UTC, thomas694 requested changes
It looks good now. 🙂 
Only a small tiny bit of cleanup and it's ok.

2022-02-12 23:12 UTC, kulesy commented on src/TumblThree/TumblThree.Applications/Controllers/CrawlerController.cs
> +                        bool isHiddenTumblrBlog = await _tumblrBlogDetector.IsHiddenTumblrBlogAsync(blog.Url);
Yes that would make more sense.

2022-02-12 23:20 UTC, kulesy commented on src/TumblThree/TumblThree.Applications/Crawler/ITumblrBlogDetector.cs
> +        Task<string> GetUrlRedirection(string url);
I should've gone back in the PR to get rid of the unnecessary changes, apologies. Teaching me a lot, thanks.

2022-02-12 23:27 UTC, kulesy commented
I'm assuming these little commits will be cleaned up in the merging process?

2022-02-12 23:46 UTC, thomas694 approved these changes
Yes, I'll do a squash merge.

2022-02-12 23:54 UTC, merged

2022-02-12 23:59 UTC, thomas694 commented
Thank you for your PR and contribution to the TumblThree project.
I'd be glad, if you like to solve the one or other issue in the future.

2022-02-13 00:04 UTC, kulesy commented
I'd be happy to help out some more.