237 hide toolbar button captions
TumblThreeApp/TumblThree pull request #477
Opened 2023-10-09 17:26 UTC by rexius41

## Checklist

_Confirm you have completed the following actions prior to submitting this PR._

 - [ ] There is an existing issue report for this PR.
 - [ ] I have forked this project.
 - [ ] I have created a feature branch.
 - [ ] My changes have been committed.
 - [ ] I have pushed my changes to the branch.

## Title

Adding option to hide text in buttons in toolbar

## Description

Hiding the text in toolbar is made by collapsing textblock, and showing tooltip on the buttons. Setting option is in settings/advanced/crawler.

## Issue Resolution

Option to hide toolbar button captions #237

This Pull Request Fixes #

## New or Changed Features

Option to hide toolbar buttons text and while hidden all buttons have the same width

2023-10-10 15:28 UTC, thomas694 requested changes
Thanks, it looks good.
I made a few suggestions, for convenience, you can mostly click "Add suggestion".

2023-10-10 15:28 UTC, thomas694 commented on src/TumblThree/TumblThree.Presentation/Properties/Resources.resx
> +    <value>Hides(colapses) the text on buttons from main application windows and leaves tooltips on so the toolbars buttons have all the same footprint</value>
Hides the text on buttons from main application window and leaves tooltips on so all the toolbar buttons have the same width
```suggestion
    <value>Hides the text on buttons from main application window and leaves tooltips on, so all the toolbar buttons have the same width</value>
```

2023-10-10 15:28 UTC, thomas694 commented on src/TumblThree/TumblThree.Presentation/Properties/Resources.de.resx
> +    <value>Verbirgt (kollabiert) den Text auf den Schaltflächen im Hauptanwendungsfenster und lässt Tooltips aktiviert, damit die Schaltflächen der Symbolleiste alle denselben Fußabdruck haben.</valu
```suggestion
    <value>Blendet den Text auf den Schaltflächen im Hauptfenster der Anwendung aus und lässt die QuickInfos eingeschaltet, so dass alle Schaltflächen in der Symbolleiste die gleiche Breite haben.</value>
```

2023-10-10 15:41 UTC, rexius41 commented on src/TumblThree/TumblThree.Presentation/Views/SettingsView.xaml
will move it there, accidently clicked the review button before making this change

2023-10-10 15:51 UTC, rexius41 commented on src/TumblThree/TumblThree.Presentation/Views/SettingsView.xaml
Added it to the General tab as the last checkbox

2023-10-10 16:24 UTC, rexius41 commented on src/TumblThree/TumblThree.Presentation/Views/CrawlerView.xaml
Done it plus changed the tooltip that is shown only when the text is hiden so it does not obstruct user when he has text in the button

2023-10-10 16:27 UTC, rexius41 commented on src/TumblThree/TumblThree.Applications/ViewModels/SettingsViewModel.cs
> +using System.Waf.Foundation;
removed not necessery/autofill

2023-10-11 19:09 UTC, thomas694 approved these changes
Thanks for your PR.

2023-10-11 19:17 UTC, merged